[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "10.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200